export const ActionTypes = {
    GET_HOME_PAGE_REC_REQUEST: 'GET_HOME_PAGE_REC_REQUEST',
    GET_HOME_PAGE_REC_SUCCESS: 'GET_HOME_PAGE_REC_SUCCESS',
    GET_HOME_PAGE_REC_FAILURE: 'GET_HOME_PAGE_REC_FAILURE',
  };
  